@extends('master')
@section('pageurl') Test Page @stop
@section('pagetitle') Test @stop
@section('content')

<form action="/PrintJob" method="post">
	{{ csrf_field() }}
	
	<input type="submit" value="Print">
	<a href="#" onclick="jsWebClientPrint.print('sid={{ $sid }}');">Print...</a>

</form>

@stop
@section('script')

{!! 

// Register the WebClientPrint script code
// The $wcpScript was generated by DemoPrintFileController@index

$wcpScript;

!!}
@endsection